/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/blank': RouteRecordInfo<'/blank', '/blank', Record<never, never>, Record<never, never>>,
    'ui-examples': RouteRecordInfo<'ui-examples', '/example', Record<never, never>, Record<never, never>>,
    '/example/axios': RouteRecordInfo<'/example/axios', '/example/axios', Record<never, never>, Record<never, never>>,
    'buttons': RouteRecordInfo<'buttons', '/example/button', Record<never, never>, Record<never, never>>,
    'card': RouteRecordInfo<'card', '/example/card', Record<never, never>, Record<never, never>>,
    '/example/chart': RouteRecordInfo<'/example/chart', '/example/chart', Record<never, never>, Record<never, never>>,
    '/example/chart-js': RouteRecordInfo<'/example/chart-js', '/example/chart-js', Record<never, never>, Record<never, never>>,
    '/example/datepicker': RouteRecordInfo<'/example/datepicker', '/example/datepicker', Record<never, never>, Record<never, never>>,
    '/example/form': RouteRecordInfo<'/example/form', '/example/form', Record<never, never>, Record<never, never>>,
    '/example/grid': RouteRecordInfo<'/example/grid', '/example/grid', Record<never, never>, Record<never, never>>,
    '/example/highlightText': RouteRecordInfo<'/example/highlightText', '/example/highlightText', Record<never, never>, Record<never, never>>,
    '/example/icon-example': RouteRecordInfo<'/example/icon-example', '/example/icon-example', Record<never, never>, Record<never, never>>,
    '/example/image-render': RouteRecordInfo<'/example/image-render', '/example/image-render', Record<never, never>, Record<never, never>>,
    '/example/openapi-ts': RouteRecordInfo<'/example/openapi-ts', '/example/openapi-ts', Record<never, never>, Record<never, never>>,
    '/example/popup': RouteRecordInfo<'/example/popup', '/example/popup', Record<never, never>, Record<never, never>>,
    '/example/progress-bar': RouteRecordInfo<'/example/progress-bar', '/example/progress-bar', Record<never, never>, Record<never, never>>,
    '/example/progress-circular': RouteRecordInfo<'/example/progress-circular', '/example/progress-circular', Record<never, never>, Record<never, never>>,
    '/example/radial-progress': RouteRecordInfo<'/example/radial-progress', '/example/radial-progress', Record<never, never>, Record<never, never>>,
    '/example/tree': RouteRecordInfo<'/example/tree', '/example/tree', Record<never, never>, Record<never, never>>,
    '/example/tree-grid-example': RouteRecordInfo<'/example/tree-grid-example', '/example/tree-grid-example', Record<never, never>, Record<never, never>>,
    'date-picker': RouteRecordInfo<'date-picker', '/example/vue-date-picker', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/maintenancePage': RouteRecordInfo<'/maintenancePage', '/maintenancePage', Record<never, never>, Record<never, never>>,
    '/mgmt/': RouteRecordInfo<'/mgmt/', '/mgmt', Record<never, never>, Record<never, never>>,
    '/mgmt/preparing': RouteRecordInfo<'/mgmt/preparing', '/mgmt/preparing', Record<never, never>, Record<never, never>>,
    '/not-accessible': RouteRecordInfo<'/not-accessible', '/not-accessible', Record<never, never>, Record<never, never>>,
    '/preparing': RouteRecordInfo<'/preparing', '/preparing', Record<never, never>, Record<never, never>>,
  }
}
